#服务器
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
    protocol-header-https-value: https
    protocol-header: X-Forwarded-Proto


spring:
  #数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sakila?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456


#单数据源可以这样配置，多数据源需要专门的配置文件配置
mybatis:
  mapper-location: classpath*:mapper/*.xml